### ISSUE TITLE
"No renderer could be found for mimetype "application/json""

### ISSUE THREAD

**Issue by wrgrant** [bigbug/vscode-language-jsonata#1]
This extension is awesome!
So neat to be able to save complex sequence of queries notebook style.

VSCode broke something recently though.

Everything was working fine under VSCode v1.64.2 (Windows 10)

But now that I updated to the latest (as of now) v1.65.2

I'm getting errors like this: 
![image](https://user-images.githubusercontent.com/3092780/160680030-bbb9c06f-a2d3-4026-8b4a-2c61de2c533f.png)

Please let me know if I can provide any other debugging information that would be useful.

**Comment by wrgrant** [comment]
Also, this behavior is identical on two different workstations, both running Windows 10 and the same version of VSCode.

**Comment by bigbug** [comment]
Thank you for making me aware of this. Will have a look at this at the end of the week.

**Comment by bigbug** [comment]
Just published 0.3.1 which should fix this for now.
