### ISSUE TITLE
How to "import" a common set of jsonata functions that I have created

### ISSUE THREAD

**Issue by radhakrishnan-chandarasikharan-kr** [bigbug/vscode-language-jsonata#3]
I have a few helper functions that I use in my notebooks. Instead of copying it each time into a new notebook is there a way to include one or more files into the notebook. Something like an import function.

**Comment by bigbug** [comment]
That's a good extension idea. I will see what I can do.

**Comment by bigbug** [comment]
Implemented with `$import()` in 1.0.0 (among other new functions)
