### ISSUE TITLE
Error parsing `&` expressions

### ISSUE THREAD

**Issue by Haltarys** [bigbug/vscode-language-jsonata#5]
![image](https://github.com/bigbug/vscode-language-jsonata/assets/45515869/1f005ce2-aacd-42c3-baa5-13f8a3719fd4)

It seems that having `" "` in the middle of the expression makes the left-hand side considered a string even though it is outside the quotes. Here, `client.firstName` should be blue no matter what.

It probably happens with other types of expressions and more complex ones too.

**Comment by bigbug** [comment]
Fixed with 1.0.0
